export const ADD_DISHES='ADD_DISHES';
export const DISHES_LOADING='DISHES_LOADING';
export const DISHES_FAILED='DISHES_FAILED';

//comment

export const ADD_COMMENTS='ADD_COMMENTS';
export const COMMENTS_FAILED='COMMENTS_FAILED';

//promotions
export const ADD_PROMOTIONS='ADD_PROMOTIONS';
export const PROMOTIONS_LOADING='PROMOTIONS_LOADING';
export const PROMOTIONS_FAILED='PROMOTIONS_FAILED';

//leaders
export const ADD_LEADERS='ADD_LEADERS';
export const LEADERS_LOADING='LEADERS_LOADING';
export const LEADERS_FAILED='LEADERS_FAILED';